# Generated by Django 5.2.8 on 2025-11-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
